version: 2.18.1
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9999:8000
  auth:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081