version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile_app
    ports:
      - 8001:8001
  gui:
    build:
      context: .
      dockerfile: Dockerfile_gui
    environment:
      - DISPLAY=:0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    depends_on:
      - app