version: 2.18.1
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9999:8000
-
  loguru:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs:/fastapi_app/logs